language: python
python:
#only supporting python 2 at the moment due to COREML
  - "2.7"
# command to install dependencies


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pyaudio python3-pyaudio libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0
  - wget https://www.dropbox.com/s/2n897gu5p3o2391/libri-timit-lm.klm --directory-prefix=./lm/

install: "pip install -r requirements.txt"
# command to run tests
script:
  - python run-train.py --batchsize 2 --epochs 2
